### ISSUE TITLE
Video Skipper not working 

### ISSUE THREAD

**Issue by vrakk** [Subatomicmc/Edgenuity-Brainly-Scripts#3]
downloaded all tweaks from the site, everything seems to be working except the video watcher. When I am on the course map I do not see it pop up in the taper monkey extension bar. When I am in the instruction the videos do not auto advance. Tried on SIS and regular edgenuity. 
Pls help, can send logs if needed.

**Comment by Subatomicmc** [comment]
you gotta refresh the page and then itll pop up lol. also the autoadvance is handled by edgentweak so
