### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by pluto397** [Subatomicmc/Edgenuity-Brainly-Scripts#5]
The script is not working, but it was working a while ago.

**Comment by pluto397** [comment]
> 
> 
> The script is not working, but it was working a while ago.
Is it only working for certain assignments, because its working for my quiz, but not my online content?

**Comment by isuckatcomputers** [comment]
It doesn't work for me either, I tried to use it on brainly.com, and the third question I asked the popup appeared over the answer and won't go away. (yes the answer unhider is on and I toggled it to see if it would work but it still doesn't) Please help im terrible at this stuff and I need the answers to finish my quiz.

**Comment by Subatomicmc** [comment]
dont care

**Comment by XKingzT** [comment]
Lol that's screwed. I will make an updated version. Look onto r/edgenuity reddit for a update. Along with an Automatic Quiz/Test Answer Mod. Just figured it out. - XKingzT

**Comment by Kinotiji** [comment]
> Lol that's screwed. I will make an updated version. Look onto r/edgenuity reddit for a update. Along with an Automatic Quiz/Test Answer Mod. Just figured it out. - XKingzT

hey can you contact me on discord | mru#0001

**Comment by ayysauce** [comment]
> Lol that's screwed. I will make an updated version. Look onto r/edgenuity reddit for a update. Along with an Automatic Quiz/Test Answer Mod. Just figured it out. - XKingzT

yo man sorry for replying hella long after you posted this but i really need this man so if youve done it it would be greatly appreciated man
